version: "3.8"

services:
  directus:
    image: directus/directus:11.14.0
    ports:
      - "8055:8055"
    environment:
      KEY: super-secret-key
      SECRET: super-secret-secret

      DB_CLIENT: sqlite3
      DB_FILENAME: /directus/database/database.sqlite

      CORS_ENABLED: "true"
      CORS_ORIGIN: "*"

      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: admin123

    volumes:
      - directus_database:/directus/database
      - directus_uploads:/directus/uploads

volumes:
  directus_database:
  directus_uploads:
